export type Attribute =
  | "accesskey"
  | "autocapitalize"
  | "autofocus"
  | "class"
  | "contenteditable"
  | "dir"
  | "draggable"
  | "enterkeyhint"
  | "hidden"
  | "id"
  | "inputmode"
  | "is"
  | "itemid"
  | "itemprop"
  | "itemref"
  | "itemscope"
  | "itemtype"
  | "lang"
  | "nonce"
  | "slot"
  | "spellcheck"
  | "style"
  | "tabindex"
  | "title"
  | "translate"
  | "charset"
  | "coords"
  | "download"
  | "href"
  | "hreflang"
  | "name"
  | "ping"
  | "referrerpolicy"
  | "rel"
  | "rev"
  | "shape"
  | "target"
  | "type"
  | "align"
  | "alt"
  | "archive"
  | "code"
  | "codebase"
  | "height"
  | "hspace"
  | "object"
  | "vspace"
  | "width"
  | "nohref"
  | "autoplay"
  | "controls"
  | "crossorigin"
  | "loop"
  | "muted"
  | "preload"
  | "src"
  | "color"
  | "face"
  | "size"
  | "cite"
  | "alink"
  | "background"
  | "bgcolor"
  | "link"
  | "text"
  | "vlink"
  | "clear"
  | "disabled"
  | "form"
  | "formaction"
  | "formenctype"
  | "formmethod"
  | "formnovalidate"
  | "formtarget"
  | "value"
  | "char"
  | "charoff"
  | "span"
  | "valign"
  | "datetime"
  | "open"
  | "compact"
  | "accept"
  | "accept-charset"
  | "action"
  | "autocomplete"
  | "enctype"
  | "method"
  | "novalidate"
  | "frameborder"
  | "longdesc"
  | "marginheight"
  | "marginwidth"
  | "noresize"
  | "scrolling"
  | "cols"
  | "rows"
  | "profile"
  | "noshade"
  | "manifest"
  | "version"
  | "allow"
  | "allowfullscreen"
  | "allowpaymentrequest"
  | "allowusermedia"
  | "loading"
  | "sandbox"
  | "srcdoc"
  | "border"
  | "decoding"
  | "ismap"
  | "sizes"
  | "srcset"
  | "usemap"
  | "checked"
  | "dirname"
  | "list"
  | "max"
  | "maxlength"
  | "min"
  | "minlength"
  | "multiple"
  | "pattern"
  | "placeholder"
  | "readonly"
  | "required"
  | "step"
  | "prompt"
  | "for"
  | "as"
  | "imagesizes"
  | "imagesrcset"
  | "integrity"
  | "media"
  | "content"
  | "http-equiv"
  | "scheme"
  | "high"
  | "low"
  | "optimum"
  | "classid"
  | "codetype"
  | "data"
  | "declare"
  | "standby"
  | "typemustmatch"
  | "reversed"
  | "start"
  | "label"
  | "selected"
  | "valuetype"
  | "async"
  | "defer"
  | "language"
  | "nomodule"
  | "cellpadding"
  | "cellspacing"
  | "frame"
  | "rules"
  | "summary"
  | "abbr"
  | "axis"
  | "colspan"
  | "headers"
  | "nowrap"
  | "rowspan"
  | "scope"
  | "wrap"
  | "default"
  | "kind"
  | "srclang"
  | "playsinline"
  | "poster"

/**
 * - = : equals
 * - ~= : contains
 * - |= : starts with (note: value has to be a whole word, either alone, like lang="en", or followed by a hyphen)
 * - ^= : starts with (note: value can be anything)
 * - $= : ends with
 * - *= : contains
 */
export type Matcher = "=" | "~=" | "|=" | "^=" | "$=" | "*="

/**
 * if value is a string it acts as the `[attribute]` selector meaning that it will target all elements that just have that attribute
 */
export type Selector =
  | Attribute
  | [attribute: Attribute, matcher: Matcher, value: string]

export type ClassName = string

export type Config = Record<ClassName, Selector>
